var s1 = '  Ramesha',s2 = '    gowda',s3 = '  mahesha',s4 = ' sowbhagya',s5 = ' srinivas';
var s6 = '  manjula',s7 = '   govindha',s8 = '  kavya',s9 = '    hema',s10 = '    mahadev';
console.log('-------------------------------------------------');
console.log('uppercase value is',s1.toUpperCase());
console.log('uppercase value is',s2.toUpperCase());
console.log('uppercase value is',s3.toUpperCase());
console.log('uppercase value is',s4.toUpperCase());
console.log('uppercase value is',s5.toUpperCase());
console.log('uppercase value is',s6.toUpperCase());
console.log('uppercase value is',s7.toUpperCase());
console.log('uppercase value is',s8.toUpperCase());
console.log('uppercase value is',s9.toUpperCase());
console.log('uppercase value is',s10.toUpperCase());
console.log('-------------------------------------------------');
console.log('lowercase value is',s1.toLowerCase());
console.log('lowercase value is',s2.toLowerCase());
console.log('lowercase value is',s3.toLowerCase());
console.log('lowercase value is',s4.toLowerCase());
console.log('lowercase value is',s5.toLowerCase());
console.log('lowercase value is',s6.toLowerCase());
console.log('lowercase value is',s7.toLowerCase());
console.log('lowercase value is',s8.toLowerCase());
console.log('lowercase value is',s9.toLowerCase());
console.log('lowercase value is',s10.toLowerCase());
console.log('-------------------------------------------------');
console.log('char at given position is',s1.charAt(4));
console.log('char at given position is',s2.charAt(4));
console.log('char at given position is',s3.charAt(4));
console.log('char at given position is',s4.charAt(4));
console.log('char at given position is',s5.charAt(4));
console.log('char at given position is',s6.charAt(4));
console.log('char at given position is',s7.charAt(4));
console.log('char at given position is',s8.charAt(4));
console.log('char at given position is',s9.charAt(4));
console.log('char at given position is',s10.charAt(4));
console.log('-------------------------------------------------');
console.log('index of given char is',s1.indexOf('a'));
console.log('index of given char is',s2.indexOf('w'));
console.log('index of given char is',s3.indexOf('h'));
console.log('index of given char is',s4.indexOf('b'));
console.log('index of given char is',s5.indexOf('r'));
console.log('index of given char is',s6.indexOf('l'));
console.log('index of given char is',s7.indexOf('v'));
console.log('index of given char is',s8.indexOf('v'));
console.log('index of given char is',s9.indexOf('m'));
console.log('index of given char is',s10.indexOf('d'));
console.log('-------------------------------------------------');
console.log('new string is',s1.concat(' intorocks'));
console.log('new string is',s2.concat(' intorocks'));
console.log('new string is',s3.concat(' intorocks'));
console.log('new string is',s4.concat(' intorocks'));
console.log('new string is',s5.concat(' intorocks'));
console.log('new string is',s6.concat(' intorocks'));
console.log('new string is',s7.concat(' intorocks'));
console.log('new string is',s8.concat(' intorocks'));
console.log('new string is',s9.concat(' intorocks'));
console.log('new string is',s10.concat(' intorocks'));
console.log('-------------------------------------------------');
console.log('does the string include given char?',s1.includes('s'));
console.log('does the string include given char?',s2.includes('a'));
console.log('does the string include given char?',s3.includes('v'));
console.log('does the string include given char?',s4.includes('r'));
console.log('does the string include given char?',s5.includes('o'));
console.log('does the string include given char?',s6.includes('e'));
console.log('does the string include given char?',s7.includes('r'));
console.log('does the string include given char?',s8.includes('i'));
console.log('does the string include given char?',s9.includes('p'));
console.log('does the string include given char?',s10.includes('h'));
console.log('-------------------------------------------------');
console.log('new string is',s1.replace('esha','intorocks'));
console.log('new string is',s2.replace('a','intorocks'));
console.log('new string is',s3.replace('m','intorocks'));
console.log('new string is',s4.replace('a','intorocks'));
console.log('new string is',s5.replace('sri','intorocks'));
console.log('new string is',s6.replace('man','intorocks'));
console.log('new string is',s7.replace('dha','intorocks'));
console.log('new string is',s8.replace('ya','intorocks'));
console.log('new string is',s9.replace('ma','intorocks'));
console.log('new string is',s10.replace('h','intorocks'));
console.log('-------------------------------------------------');
console.log('array of string is',s1.split('a'));
console.log('array of string is',s2.split('w'));
console.log('array of string is',s3.split('a'));
console.log('array of string is',s4.split('o'));
console.log('array of string is',s5.split('i'));
console.log('array of string is',s6.split('j'));
console.log('array of string is',s7.split('v'));
console.log('array of string is',s8.split('v'));
console.log('array of string is',s9.split('m'));
console.log('array of string is',s10.split('h'));
console.log('-------------------------------------------------');
console.log('new string is',s1.substr(0,3));
console.log('new string is',s2.substr(4));
console.log('new string is',s3.substr(4));
console.log('new string is',s4.substr(4));
console.log('new string is',s5.substr(4));
console.log('new string is',s6.substr(4));
console.log('new string is',s7.substr(4));
console.log('new string is',s8.substr(4));
console.log('new string is',s9.substr(4));
console.log('new string is',s10.substr(4));
console.log('-------------------------------------------------');
console.log('value of string is',s1.search('ra'));
console.log('value of string is',s2.search('da'));
console.log('value of string is',s3.search('h'));
console.log('value of string is',s4.search('so'));
console.log('value of string is',s5.search('sr'));
console.log('value of string is',s6.search('ju'));
console.log('value of string is',s7.search('go'));
console.log('value of string is',s8.search('ya'));
console.log('value of string is',s9.search('ma'));
console.log('value of string is',s10.search('de'));
console.log('-------------------------------------------------');
console.log('string without spaces is',s1.trim());
console.log('string without spaces is',s2.trim());
console.log('string without spaces is',s3.trim());
console.log('string without spaces is',s4.trim());
console.log('string without spaces is',s5.trim());
console.log('string without spaces is',s6.trim());
console.log('string without spaces is',s7.trim());
console.log('string without spaces is',s8.trim());
console.log('string without spaces is',s9.trim());
console.log('string without spaces is',s10.trim());