const hobbies = ['traveling','cooking','bike riding','eating','sleeping'];
console.log('hobbies',hobbies);
console.log('type ',typeof hobbies);
console.log('is it an array?',Array.isArray(hobbies));
console.log('does it include cooking',hobbies.includes('cooking'));
console.log('does it include cooking after 6th index',hobbies.includes('cooking',6));
console.log('new length of array is',hobbies.push('coding','movies'));
console.log('the last element is ',hobbies.pop());
console.log('hobbies',hobbies);
console.log('new length of array is ',hobbies.unshift('numismatics','reading'));
console.log('hobbies',hobbies);
console.log('the first element is',hobbies.shift());
console.log('hobbies',hobbies); 
console.log('new length');
console.log('removed elements are',hobbies.splice(1,2));
console.log('hobbies',hobbies);
console.log('removed elements are',hobbies.splice(1,2,'PUBG','gardening'));
console.log('hobbies',hobbies);
console.log(hobbies.splice(1,0,'traveling','cooking'));
console.log('hobbies',hobbies);
console.log('removed elements are',hobbies.slice(1,5));
console.log('hobbies',hobbies);
console.log('PUBG is at index number',hobbies.indexOf('PUBG'));
console.log('string value of array separated by - is',hobbies.join('-'));
console.log('string value of array separated by , is',hobbies.join());
console.log('string value of array separated by _ is',hobbies.join('_'));
console.log('string value of array separated by * is',hobbies.join('*'));
var n = [100,200,300,400]
console.log('**new array with elements incresed by 25 is',n.map(function(v){return v+25}));
console.log('**new array with elements incresed by 50 is',n.map(value=>value+50));
console.log('**elements greater 150',n.filter(v=>{var b = v>150;return b;}));
console.log('**elements greater 200',n.filter(v=>v>200));